services:
  api-gateway:
    build: ./api-gateway
    ports: ["8000:8000"]
    environment:
      - ML_URL=http://ml-service:8001
      - LLM_URL=http://llm-service:8002
    depends_on: [ml-service, llm-service]

  ml-service:
    build: ./ml-service
    ports: ["8001:8001"]

  llm-service:
    build: ./llm-service
    ports: ["8002:8002"]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}

  web-app:
    build: ./web-app
    ports: ["3000:3000"]
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on: [api-gateway]
